### ISSUE TITLE
Problem with closing app, after connecting callback

### ISSUE THREAD

**Issue by PatrykSajdok** [simpleble/simpleble#28]
I'm using this library in Unity. I've added simple methods in it to configure everything with simple commands, like `ConnectToDevice(deviceId, timeout, ConnectCallback, DisconnectCallback)`. I also have `DebugCallback` so if any error will happen in the library, I will know about it in C#. The problem is that if I will call any of my callbacks (Debug, Connection etc) everything is working, but if Callback from the library (`set_callback_on_connected` for example) will call any of my callbacks, then I will not be able to close the application (it will freeze on exit)

**Comment by kdewald** [comment]
It's possible that you are running into some sort of deadlock. Environments like Unity usually have strict requirements for how callbacks are received and processed. So I wouldn't be surprised if there is some additional abstraction layer required. Do you have some sample code to look at?

**Comment by PatrykSajdok** [comment]
I have no idea why github formatted code like this

**Comment by kdewald** [comment]
Ok, I did a bit of research on the topic. Apparently this is caused by a limitation on how Unity handles multithreading. (Long story short, it doesn't.) Basically it uses a set of locks to prevent multiple functions from running at one.

The deadlock happens in this situation:
- You call `connect()` from Unity's main thread (thread 1)
- `connect()` will internally make all the necessary operating system calls.
- The operating system will issue an event from a *different* thread (thread 2)
- This event will attempt to call your callback, which in turn will likely interact with the Unity backend.
- Unity will prevent thread 2 from executing until thread 1 finishes. But thread 1 needs thread 2 to return before continuing, so you've entered a deadlock and the program freezes.

There's not much that can be done here (at least with my current knowledge) besides not using these internal callbacks. I have some ideas for changes within the library that could allow this from working, but it will take some time until I properly figure it out.
